alpha: 0.2
automatic_entropy_tuning: true
batch_size: 256
cores: 2
cuda: 0
env_name: Hopper-v2
eval: true
exp_id: hopper
gamma: 0.99
hidden_size: 256
lr: 0.0003
num_steps: 1000000
policy: Gaussian
replay_size: 1000000
seed: 2021
start_steps: 10000
target_update_interval: 1
tau: 0.005
updates_per_step: 1
